blank_issues_enabled: false
contact_links:
  - name: QLC+ documentation
    url: https://docs.qlcplus.org/
    about: Use official QLC+ documentation for general QLC+ questions unrelated to this integration.
